name: CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run unit tests
        run: mvn test -B

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Publish JaCoCo report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

  upload-ftp:
    needs: test-unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create JaCoCo report directory
        run: mkdir -p target/site/jacoco/

      - name: Upload JaCoCo report via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: joaobsjunior.com.br
          username: aluno-ftp
          password: a1b2c3d4@
          local-dir: target/site/jacoco/
          server-dir: /public_html/Gerenciamento-de-Estoque-A3-master/

  test-integration:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run integration tests
        run: mvn verify -B

      - name: Generate JaCoCo report for integration tests
        run: mvn jacoco:report

      - name: Publish JaCoCo report for integration tests
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report-integration
          path: target/site/jacoco/

  release:
    if: github.ref == 'refs/heads/release'
    needs: [upload-ftp, test-integration]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Application
        run: echo "Deploying application..."

  sonarqube:
    needs: test-unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=ProjetoA3 -Dsonar.organization=grbadas -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
