name: CI/CD

on:
  push:
    branches:
      - master
      - Development
      - release
  pull_request:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run unit tests
        run: mvn test -B

      - name: Run integration tests
        run: mvn verify -B

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: List files in target directory
        run: ls -R target/

      - name: Verify JaCoCo report directory
        run: |
          echo "Checking JaCoCo report directory"
          if [ -d "target/site/jacoco/" ]; then
            echo "JaCoCo report directory exists"
            ls -l target/site/jacoco/
          else
            echo "JaCoCo report directory does not exist"
            exit 1
          fi

      - name: Publish JaCoCo report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

  upload-ftp:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify JaCoCo report directory before upload
        run: |
          echo "Checking JaCoCo report directory before upload"
          if [ -d "target/site/jacoco/" ]; then
            echo "JaCoCo report directory exists"
            ls -l target/site/jacoco/
          else
            echo "JaCoCo report directory does not exist"
            exit 1
          fi

      - name: Upload JaCoCo report via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: target/site/jacoco/
          server-dir: /public_html/Gerenciamento-de-Estoque-A3-master/

  release:
    if: github.ref == 'refs/heads/release'
    needs: upload-ftp
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Deploy Application
        run: echo "Deploying application..."

  versioning:
    if: github.ref == 'refs/heads/release'
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Versioning Script
        run: |
          chmod +x .github/workflows/generateVersion.sh
          .github/workflows/generateVersion.sh true

  sonarqube:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=ProjetoA3 -Dsonar.organization=grbadas -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
